#!/usr/bin/env bash
# Haproxy installation and config

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" | sudo tee /etc/default/haproxy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
echo "
listen web_lb
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 208150-web-01 100.25.158.180:80 check
   server 208150-web-02 100.26.253.232:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy start
