#!/usr/bin/env bash
# Haproxy installation and config

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
echo "
frontend web_front
   bind *:80
   mode http
   default_backend web_back

backend web_back
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 208150-web-01 100.25.158.180:80 check
   server 208150-web-02 100.26.253.232:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start