#!/usr/bin/env bash
# Installs and configure HAProxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 208150-web-01 100.25.158.180:80 check
    server 208150-web-02 100.26.253.232:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy start
