#!/usr/bin/env bash
# Nginx is running as the nginx user.
if ! id "nginx" &>/dev/null || sudo useradd nginx
sed -i 's/# user nginx/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service nginx start
